#端口号
server:
  port: 9010
  servlet:
    context-path: /evaluation-system
  #数据源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/evaluation_system?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #jackson-date
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #transaction
  transaction:
    rollback-on-commit-failure: true
  #http
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 100
      max-request-size: 100
#jwt
jwtparam:
  issuer: ec8b63c05f999a15a8c8567002a560a8
  audience: 541bee7d2a922cc0a81ff4ca3c23f4af
  TTLMillis: 3600000
  base64Security: JXU4RDM1JXU3MTY0JXU4QkJFJXU4QkEx1
